// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpClient is an autogenerated mock type for the HttpClient type
type HttpClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: method, body
func (_m *HttpClient) Send(method string, body []byte) ([]byte, error) {
	ret := _m.Called(method, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []byte) ([]byte, error)); ok {
		return rf(method, body)
	}
	if rf, ok := ret.Get(0).(func(string, []byte) []byte); ok {
		r0 = rf(method, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(method, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHttpClient creates a new instance of HttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpClient {
	mock := &HttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
